"""add whatsapp_id and status

Revision ID: 74514ed9eca8
Revises: 8a9ae6245bba
Create Date: 2026-04-22 13:26:59.074888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74514ed9eca8'
down_revision: Union[str, Sequence[str], None] = '8a9ae6245bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('whatsapp_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'status')
    op.drop_column('messages', 'whatsapp_id')
    # ### end Alembic commands ###
