"""add is_read column

Revision ID: 8a9ae6245bba
Revises: 7fc280fee20e
Create Date: 2026-04-13 17:00:13.633840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9ae6245bba'
down_revision: Union[str, Sequence[str], None] = '7fc280fee20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agents_email'), 'agents', ['email'], unique=True)
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=True)
    op.add_column('conversations', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'agents', ['agent_id'], ['id'])
    op.add_column('messages', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_column('messages', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_column('messages', 'created_at')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'agent_id')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_index(op.f('ix_agents_email'), table_name='agents')
    # ### end Alembic commands ###
